name: Issue Numbering

on:
  issues:
    types: [opened, edited]

jobs:
  add-number-to-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add number to issue
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const issueTitle = context.payload.issue.title;
          const issueNumber = context.payload.issue.number;
          const fileName = 'ISSUE_LIST.md';

          const fs = require('fs');
          const path = require('path');

          // Check if the file exists, if not create it
          if (!fs.existsSync(fileName)) {
            fs.writeFileSync(fileName, `Issue List:\n\n`);
          }

          // Append the issue number and title to the file
          fs.appendFileSync(fileName, `#${issueNumber} - ${issueTitle}\n`);

          // Use shell commands to commit and push changes
          const exec = require('child_process').execSync;
          exec('git config --local user.email "action@github.com"');
          exec('git config --local user.name "GitHub Action"');
          exec('git add ISSUE_LIST.md');
          exec(`git commit -m "Update issue list with issue #${issueNumber}"`);
          exec('git push');
