name: Repository Dispatch
on: repository_dispatch

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run script
        run: bash path/to/your/script.sh
