name: Update File Names with Revision

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-file-names:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Update File Names with Revision
      run: |
        python rename_files_with_revision.py

    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update file names with revision
        branch: main
        file_pattern: .  # Add files/directories to commit
